apiVersion: apps/v1
kind: Deployment
metadata:
  name: available-schedules-go
  namespace: apps
  labels: { app: available-schedules-go }
spec:
  replicas: 1
  selector:
    matchLabels: { app: available-schedules-go }
  template:
    metadata:
      labels: { app: available-schedules-go }
    spec:
      containers:
        - name: available-schedules-go
          image: available-schedules-go:local
          imagePullPolicy: Never
          env:
            - name: ERROR_RATE
              value: "0.02"
            - name: EXTRA_LATENCY_MS
              value: "40"
            - name: SERVICE_NAME
              value: "available-schedules"
            # New Variables for OTEL
            - name: ENV
              value: "production"
            - name: VERSION
              value: "v1.0.1"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              # Pointing to the OTEL Collector service
              value: "tempo.observability.svc.cluster.local:4318" # OTLP HTTP endpoint
          ports:
            - containerPort: 8080
          resources:
            requests: { cpu: "40m", memory: "64Mi" } 
            limits:   { cpu: "200m", memory: "192Mi" }
