apiVersion: v1
kind: Service
metadata:
  name: available-schedules-python
  namespace: apps
  labels: { app: available-schedules-python }
spec:
  selector: { app: available-schedules-python }
  ports:
    - name: http
      port: 80
      targetPort: 8000
